# Generated by Django 5.0 on 2023-12-20 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 0, 11, 16, 390687, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
