# Generated by Django 5.0 on 2023-12-20 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 0, 13, 39, 486193, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
